### ISSUE TITLE
[BUG] Tree's going off into space

### ISSUE THREAD

**Issue by ElliotExp** [ConnorDY/OSRS-Environment-Exporter#194]
Love the software!

For some reason whenever I load an area, all the trees are stretched into space. Here's a screenshot.

![Image](https://github.com/user-attachments/assets/e4b4d9d6-c43b-4f8d-aa5c-133f97b6b442)

Thank you!

**Comment by TheHappyPittie** [comment]
I'm having this issue as well. Using cache "2024-11-20-rev227.

![Image](https://github.com/user-attachments/assets/b18c458b-5491-4745-817d-beb92c6f0abb)

**Comment by ConnorDY** [comment]
This is fixed in `main` but I haven't published the release to GitHub yet.

**Comment by ElliotExp** [comment]
Amazing! Obv no rush, but any idea when the new release will be coming? Thank you!

**Comment by DeKalipa** [comment]
Greetings.
This is still persistent. Any solution on the way?
Thank you, have a wonderful day.

**Comment by indiepunkcrow** [comment]
Bumping this as well, I'm still running in to this
